spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:postgresql://postgresql-users:5432/spring_shop_users_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/