eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    io.github.divyesh.springshop: DEBUG