# Configuration for the Product Service

server:
  port: 8082 # Let's give it a new port to prove the config server is working

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring_shop_products_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
