# Configuration for the Product Service
server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/spring_shop_products_db

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/